### ISSUE TITLE
Randomizer trouble to Sonicshadowsilver2's Garden of Assemblage Mod

### ISSUE THREAD

**Issue by ItetsuShikurasa** [afresquet/kh2fm-randomizer#2]
Hey, I just recently found out about the mod put out for KH2FM, but I was having trouble getting the randomizer to work properly. I took the codes that he provided (I am using his Randomizer Build), and I am trying to figure out where to put the codes from the seed generator in.

**Comment by afresquet** [comment]
You put both files at the cheats folder where PCSX2 is, add something at the end of the name of mod file to tell them apart and then change the randomizer file as you generate new ones.
