### ISSUE TITLE
No dark theme

### ISSUE THREAD

**Issue by zax-xyz** [afresquet/kh2fm-randomizer#22]
## Expected Behavior
The site has a dark theme option :)

## Actual Behavior
The site has no dark theme option :(

## Steps to Reproduce the Problem

  1. Open the website
  2. Search around for a setting to enable the dark theme
  3. Realise there is no dark theme :(
  4. Try not to cry
  5. peepoSad

## Specifications

  - Version: 0.4.0 (WIP)
  - Platform: Firefox 80.0.1-1, Arch Linux (5.8.5-arch1-1)
  - Subsystem: None

**Comment by afresquet** [comment]
Thank you for reporting the issue, it will be fixed any time from tomorrow through 2030

**Comment by afresquet** [comment]
The React app has been removed and moved into its own repository, so this issue is now irrelevant.

Get absolutely rekt.

**Comment by afresquet** [comment]
I was young and foolish back then, I have since grown not only as a developer, but as a man.

I reopen this issue and will _issue_ my most sincere apologies.

You're still a nerd.

**Comment by afresquet** [comment]
antd is awful to set a theme toggle so I changed the theme entirely.

Any white theme maximalists please direct your hate to Mr @zaxutic
