### ISSUE TITLE
Discord link has expired

### ISSUE THREAD

**Issue by Nicholas-Steel** [afresquet/kh2fm-randomizer#34]
I've set my Playstation 2 Setup Guide to private since I was seemingly arbitrarily banned from the Discord. I try to improve the experience for newcomers and the thanks I get is a ban.

The newest version of the guide: https://docs.google.com/document/d/1labcp77jnOzBNV_pjhk5nftFFtOvaijF-Kj-UVkafKY

**Comment by afresquet** [comment]
I've updated the link and it will be live when I deploy it.
